# Introduction to NumPy

In [ ]:
#Python lists are not as fast as numpy because they can take in different data types in one list whilst numpy subjects 
#everything to one data type e.g a mixture of numbers and text is converted to text
#If you want to use a package that is not available in your browser,you write "pip install name of package" then run

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
d = [1,3,5,2,8,23]

In [4]:
type(d)

list

In [5]:
s = np.array(d)

In [6]:
type(s)

numpy.ndarray

In [7]:
s.dtype

dtype('int32')

In [8]:
s.ndim

1

In [9]:
s.shape

(6,)

In [10]:
s.size

6

In [11]:
c = [[2,3,4,5,1,2,3],[5,4,5,6,7,4,3],[5,3,5,7,9,4,1]]

In [12]:
c

[[2, 3, 4, 5, 1, 2, 3], [5, 4, 5, 6, 7, 4, 3], [5, 3, 5, 7, 9, 4, 1]]

In [13]:
u = np.array(c, dtype = np.int16)
u

array([[2, 3, 4, 5, 1, 2, 3],
       [5, 4, 5, 6, 7, 4, 3],
       [5, 3, 5, 7, 9, 4, 1]], dtype=int16)

In [14]:
u.ndim

2

In [15]:
u.shape

(3, 7)

In [16]:
u.size

21

In [17]:
u.dtype

dtype('int16')

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(2,14)#start at 2 and end at 14

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [20]:
np.arange(2,14,3,dtype = float)# start at 2 and end at 14 while adding 4 each time

array([ 2.,  5.,  8., 11.])

In [21]:
np.linspace(2,20,5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [22]:
np.linspace(2,8)#generates 50 numbers in the range of the two given numbers with decimal numbers(dtype=int16 makes them integers)

array([2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
       2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
       3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
       3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
       4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
       5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
       5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
       6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
       6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
       7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ])

In [23]:
np.eye(4,dtype = np.int16)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

In [24]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [25]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [26]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [27]:
np.diag([2,3,4,5,7],2)

array([[0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 7],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [28]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [29]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.full(7,9)

array([9, 9, 9, 9, 9, 9, 9])

In [31]:
np.linspace(2,8).reshape(2,25).shape

(2, 25)

In [32]:
np.linspace(2,8).reshape(2,25)

array([[2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
        2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
        3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
        3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
        4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551],
       [5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
        5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
        6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
        6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
        7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ]])

In [33]:
np.linspace(2,8).reshape(5,10)

array([[2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
        2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082],
       [3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
        3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061],
       [4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
        5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041],
       [5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
        6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ],
       [6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
        7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ]])

In [34]:
np.arange(2,40).shape

(38,)

In [36]:
np.arange(2,40).reshape(2,19)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39]])

In [37]:
np.arange(1,37).shape

(36,)

In [38]:
np.arange(1,37).reshape(6,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [39]:
np.transpose(np.arange(1,37).reshape(6,6))

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

In [45]:
a = np.array([1,2,3])
c = np.array([[9,0,12],[76,9,21]])
b = np.array([[9,6,8],[9,1,6]])

In [46]:
a

array([1, 2, 3])

In [47]:
b

array([[9, 6, 8],
       [9, 1, 6]])

In [48]:
np.vstack([a,b])

array([[1, 2, 3],
       [9, 6, 8],
       [9, 1, 6]])

In [49]:
np.hstack([b,c])

array([[ 9,  6,  8,  9,  0, 12],
       [ 9,  1,  6, 76,  9, 21]])

In [50]:
c*b

array([[ 81,   0,  96],
       [684,   9, 126]])

In [52]:
o =np.array([2,3,4])
w =np.array([3,4,5])


In [53]:
o-w

array([-1, -1, -1])

In [55]:
np.subtract(o,w)

array([-1, -1, -1])

In [56]:
o+w

array([5, 7, 9])

In [57]:
np.add(o,w)

array([5, 7, 9])

In [58]:
o/w

array([0.66666667, 0.75      , 0.8       ])

In [59]:
np.divide(o,w)

array([0.66666667, 0.75      , 0.8       ])

In [60]:
o*w

array([ 6, 12, 20])

In [61]:
np.multiply(o,w)

array([ 6, 12, 20])

Aggregate functions

In [64]:
o

array([2, 3, 4])

In [65]:
o.sum()

9

In [66]:
np.transpose(np.arange(1,37).reshape(6,6)).sum()

666

In [67]:
np.transpose(np.arange(1,37).reshape(6,6)).sum(axis=0)#sum of the columns

array([ 21,  57,  93, 129, 165, 201])

In [68]:
np.transpose(np.arange(1,37).reshape(6,6)).sum(axis=1)#sum of the rows

array([ 96, 102, 108, 114, 120, 126])

In [69]:
np.transpose(np.arange(1,37).reshape(6,6))

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

In [70]:
import pandas as pd

In [71]:
pd.DataFrame(np.transpose(np.arange(1,37).reshape(6,6)))

0   1   2   3   4   5
0  1   7  13  19  25  31
1  2   8  14  20  26  32
2  3   9  15  21  27  33
3  4  10  16  22  28  34
4  5  11  17  23  29  35
5  6  12  18  24  30  36

In [72]:
np.transpose(np.arange(1,37).reshape(6,6)).min()

1

In [74]:
np.transpose(np.arange(1,37).reshape(6,6)).min(axis=0)

array([ 1,  7, 13, 19, 25, 31])

In [75]:
np.transpose(np.arange(1,37).reshape(6,6)).min(axis=1)

array([1, 2, 3, 4, 5, 6])

In [76]:
np.transpose(np.arange(1,37).reshape(6,6)).max(axis=0)

array([ 6, 12, 18, 24, 30, 36])

In [78]:
np.transpose(np.arange(1,37).reshape(6,6)).max(axis=1)

array([31, 32, 33, 34, 35, 36])

In [79]:
np.transpose(np.arange(1,37).reshape(6,6)).cumsum(axis=0)

array([[  1,   7,  13,  19,  25,  31],
       [  3,  15,  27,  39,  51,  63],
       [  6,  24,  42,  60,  78,  96],
       [ 10,  34,  58,  82, 106, 130],
       [ 15,  45,  75, 105, 135, 165],
       [ 21,  57,  93, 129, 165, 201]])

In [80]:
np.transpose(np.arange(1,37).reshape(6,6)).cumsum(axis=1)

array([[  1,   8,  21,  40,  65,  96],
       [  2,  10,  24,  44,  70, 102],
       [  3,  12,  27,  48,  75, 108],
       [  4,  14,  30,  52,  80, 114],
       [  5,  16,  33,  56,  85, 120],
       [  6,  18,  36,  60,  90, 126]])

In [81]:
np.transpose(np.arange(1,37).reshape(6,6)).cumsum(axis=0).mean()

61.833333333333336

In [82]:
np.transpose(np.arange(1,37).reshape(6,6)).cumsum(axis=1).mean()

47.25

In [83]:
np.transpose(np.arange(1,37).reshape(6,6)).cumsum(axis=0).mean(axis=0)

array([  9.33333333,  30.33333333,  51.33333333,  72.33333333,
        93.33333333, 114.33333333])

In [84]:
np.transpose(np.arange(1,37).reshape(6,6)).cumsum(axis=0).mean(axis=1)

array([ 16.,  33.,  51.,  70.,  90., 111.])

In [86]:
np.median(np.transpose(np.arange(1,37)))

18.5

In [87]:
np.cos(np.transpose(np.arange(1,37)))

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206,
       -0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281,
        0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145,
        0.91474236,  0.83422336, -0.01327675, -0.84857027, -0.90369221,
       -0.12796369])

In [88]:
np.sin(np.transpose(np.arange(1,37)))

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
        0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162,
       -0.40403765,  0.55142668,  0.99991186,  0.52908269, -0.42818267,
       -0.99177885])

In [89]:
np.tan(np.transpose(np.arange(1,37)))

array([ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,  1.15782128e+00,
       -3.38051501e+00, -2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
       -4.52315659e-01,  6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
        4.63021133e-01,  7.24460662e+00, -8.55993401e-01,  3.00632242e-01,
        3.49391565e+00, -1.13731371e+00,  1.51589471e-01,  2.23716094e+00,
       -1.52749853e+00,  8.85165604e-03,  1.58815308e+00, -2.13489670e+00,
       -1.33526407e-01,  1.17875355e+00, -3.27370380e+00, -2.81429605e-01,
        8.87142844e-01, -6.40533120e+00, -4.41695568e-01,  6.61006041e-01,
       -7.53130148e+01, -6.23498963e-01,  4.73814720e-01,  7.75047091e+00])

In [90]:
np.quantile(np.transpose(np.arange(1,37)).std(),0.7)

10.388294694831615